/**
 * The AI score: 0 means made by humans, 100 means generated by AI.
 *
 * Trusic exists so that real musicians earn real money. The score only measures
 * AI doing the *creative* work: writing, singing, playing. Engineering tools
 * such as AI mastering, mixing assistants and stem separation are fine and never
 * affect the score. They are recorded so listeners can see them, nothing more.
 *
 * A track earns (100 - score)% of the human rate per stream. Whatever it forfeits
 * is redistributed to human-made music (see payouts.ts).
 */

export const AI_STAGES = ["composition", "lyrics", "vocals", "instrumentation", "production"] as const;
export type AiStage = (typeof AI_STAGES)[number];

export const AI_USE_LEVELS = ["none", "assisted", "generated"] as const;
export type AiUseLevel = (typeof AI_USE_LEVELS)[number];

/** `not_applicable` covers stages the track doesn't have, e.g. lyrics on an instrumental. */
export type StageDeclaration = AiUseLevel | "not_applicable";

/** AI tools that are welcome on Trusic and never change the score. */
export const ASSISTIVE_TOOLS = [
  "mastering",
  "mixing",
  "stem_separation",
  "audio_restoration",
  "pitch_correction",
  "transcription",
] as const;
export type AssistiveTool = (typeof ASSISTIVE_TOOLS)[number];

export interface AiDeclaration {
  stages: Record<AiStage, StageDeclaration>;
  assistiveTools: AssistiveTool[];
  /** Named products used, e.g. "Suno", "LANDR". Shown publicly on the track. */
  toolsUsed: string[];
  notes?: string;
}

export interface AiScoreRubric {
  version: string;
  stages: Record<AiStage, { weight: number; label: string; description: string }>;
  /** `percent` is how much of a stage's weight counts at this level of AI use. */
  levels: Record<AiUseLevel, { percent: number; label: string; description: string }>;
}

export const DEFAULT_RUBRIC: AiScoreRubric = {
  version: "2026-10",
  stages: {
    composition: {
      weight: 30,
      label: "Songwriting & composition",
      description: "Melody, chords, structure: the song itself.",
    },
    lyrics: {
      weight: 15,
      label: "Lyrics",
      description: "The words.",
    },
    vocals: {
      weight: 25,
      label: "Vocals",
      description: "The sung or spoken performance, including AI voice models and clones.",
    },
    instrumentation: {
      weight: 25,
      label: "Instruments & performance",
      description: "Played or programmed parts, beats and loops.",
    },
    production: {
      weight: 5,
      label: "Arrangement & sound design",
      description: "Arranging the parts and designing the sounds.",
    },
  },
  levels: {
    none: { percent: 0, label: "No AI", description: "Made entirely by people." },
    assisted: {
      percent: 25,
      label: "AI-assisted",
      description: "A person did the work; AI suggested ideas or helped with parts of it.",
    },
    generated: {
      percent: 100,
      label: "AI-generated",
      description: "AI produced this part (for example from a text prompt).",
    },
  },
};

export class InvalidDeclarationError extends Error {
  override name = "InvalidDeclarationError";
}

/** Validate untrusted input (e.g. a request body) into an AiDeclaration. */
export function parseAiDeclaration(input: unknown): AiDeclaration {
  if (typeof input !== "object" || input === null) {
    throw new InvalidDeclarationError("declaration must be an object");
  }
  const raw = input as Record<string, unknown>;
  const rawStages = raw.stages;
  if (typeof rawStages !== "object" || rawStages === null) {
    throw new InvalidDeclarationError("declaration.stages must be an object");
  }

  const allowed = new Set<string>([...AI_USE_LEVELS, "not_applicable"]);
  const stages = {} as Record<AiStage, StageDeclaration>;
  for (const stage of AI_STAGES) {
    const value = (rawStages as Record<string, unknown>)[stage];
    if (typeof value !== "string" || !allowed.has(value)) {
      throw new InvalidDeclarationError(`declaration.stages.${stage} must be one of ${[...allowed].join(", ")}`);
    }
    stages[stage] = value as StageDeclaration;
  }
  if (AI_STAGES.every((s) => stages[s] === "not_applicable")) {
    throw new InvalidDeclarationError("at least one stage must apply to the track");
  }

  const assistiveTools = raw.assistiveTools ?? [];
  if (
    !Array.isArray(assistiveTools) ||
    !assistiveTools.every((t) => (ASSISTIVE_TOOLS as readonly string[]).includes(t))
  ) {
    throw new InvalidDeclarationError(`assistiveTools must only contain ${ASSISTIVE_TOOLS.join(", ")}`);
  }

  const toolsUsed = raw.toolsUsed ?? [];
  if (
    !Array.isArray(toolsUsed) ||
    !toolsUsed.every((t) => typeof t === "string" && t.trim().length > 0 && t.length <= 60) ||
    toolsUsed.length > 20
  ) {
    throw new InvalidDeclarationError("toolsUsed must be a list of up to 20 short names");
  }

  if (raw.notes !== undefined && (typeof raw.notes !== "string" || raw.notes.length > 2000)) {
    throw new InvalidDeclarationError("notes must be text of at most 2000 characters");
  }

  return {
    stages,
    assistiveTools: [...new Set(assistiveTools as AssistiveTool[])],
    toolsUsed: [...new Set((toolsUsed as string[]).map((t) => t.trim()))],
    ...(raw.notes ? { notes: raw.notes as string } : {}),
  };
}

export interface StageContribution {
  stage: AiStage;
  label: string;
  declared: StageDeclaration;
  /** The stage's share of the score once not-applicable stages are removed (sums to 100). */
  effectiveWeight: number;
  /** How many score points this stage contributes. */
  points: number;
}

export interface ScoreBreakdown {
  score: number;
  rubricVersion: string;
  stages: StageContribution[];
}

/**
 * Score a declaration. Weights of not-applicable stages are spread over the rest,
 * so a fully generated instrumental still scores 100.
 */
export function scoreDeclaration(declaration: AiDeclaration, rubric: AiScoreRubric = DEFAULT_RUBRIC): ScoreBreakdown {
  const applicable = AI_STAGES.filter((s) => declaration.stages[s] !== "not_applicable");
  if (applicable.length === 0) {
    throw new InvalidDeclarationError("at least one stage must apply to the track");
  }
  const totalWeight = applicable.reduce((acc, s) => acc + rubric.stages[s].weight, 0);
  if (totalWeight <= 0) throw new InvalidDeclarationError("applicable stages have no weight");

  let numerator = 0;
  const stages: StageContribution[] = AI_STAGES.map((stage) => {
    const declared = declaration.stages[stage];
    if (declared === "not_applicable") {
      return { stage, label: rubric.stages[stage].label, declared, effectiveWeight: 0, points: 0 };
    }
    const weight = rubric.stages[stage].weight;
    const percent = rubric.levels[declared].percent;
    numerator += weight * percent;
    return {
      stage,
      label: rubric.stages[stage].label,
      declared,
      effectiveWeight: (weight / totalWeight) * 100,
      points: (weight * percent) / totalWeight,
    };
  });

  return {
    score: clampScore(Math.round(numerator / totalWeight)),
    rubricVersion: rubric.version,
    stages,
  };
}

export function clampScore(score: number): number {
  return Math.min(100, Math.max(0, Math.round(score)));
}

// ---------------------------------------------------------------------------
// Combining the artist's declaration with automated detection and human review.

export type DetectionVerdict = "likely_human" | "likely_ai" | "inconclusive";

export interface DetectionResult {
  /** Which detector produced this, e.g. "metadata-stub" or a vendor model name. */
  detector: string;
  verdict: DetectionVerdict;
  /** 0 to 1. */
  confidence: number;
  /** The detector's estimate of the AI score, if it can give one. */
  estimatedScore?: number;
  evidence: string[];
}

export interface ScorePolicy {
  /** Detection only overrides a declaration at or above this confidence. */
  detectionConfidenceThreshold: number;
  /** Detection must exceed the declared score by more than this to override it. */
  detectionTolerance: number;
}

export const DEFAULT_SCORE_POLICY: ScorePolicy = {
  detectionConfidenceThreshold: 0.9,
  detectionTolerance: 10,
};

export type ScoreSource = "declared" | "detected" | "review";

export interface ScoreResolution {
  score: number;
  source: ScoreSource;
  /** True when detection raised the score above the declaration. The artist can appeal. */
  flagged: boolean;
  reason: string;
}

/**
 * Work out a track's effective score.
 *
 * 1. A human review decision (from an appeal) always wins.
 * 2. Otherwise detection can *raise* the score, never lower it, when it is
 *    confident and clearly disagrees with the declaration.
 * 3. Otherwise the artist's declaration stands.
 */
export function resolveAiScore(
  input: { declaredScore: number; detection?: DetectionResult | null; reviewScore?: number | null },
  policy: ScorePolicy = DEFAULT_SCORE_POLICY,
): ScoreResolution {
  if (input.reviewScore !== undefined && input.reviewScore !== null) {
    return {
      score: clampScore(input.reviewScore),
      source: "review",
      flagged: false,
      reason: "Set by Trusic review.",
    };
  }

  const declared = clampScore(input.declaredScore);
  const d = input.detection;
  if (d && d.verdict === "likely_ai" && d.confidence >= policy.detectionConfidenceThreshold) {
    const detected = clampScore(d.estimatedScore ?? 100);
    if (detected > declared + policy.detectionTolerance) {
      return {
        score: detected,
        source: "detected",
        flagged: true,
        reason: `Detection (${d.detector}) found more AI than declared (${detected} vs ${declared}).`,
      };
    }
  }

  return { score: declared, source: "declared", flagged: false, reason: "Artist declaration." };
}

// ---------------------------------------------------------------------------
// Labels shown to listeners.

export type AiLabel = "human" | "ai_assisted" | "ai_generated";

export const AI_LABELS: Record<AiLabel, { name: string; description: string }> = {
  human: { name: "Human-made", description: "Written and performed by people." },
  ai_assisted: { name: "AI-assisted", description: "Made by people with significant help from AI." },
  ai_generated: { name: "AI-generated", description: "Mostly or entirely generated by AI." },
};

/** Each label covers scores from `min` up to but not including `max`. */
export const AI_LABEL_RANGES: Record<AiLabel, { min: number; max: number }> = {
  human: { min: 0, max: 10 },
  ai_assisted: { min: 10, max: 70 },
  ai_generated: { min: 70, max: 101 },
};

export function aiLabel(score: number): AiLabel {
  const s = clampScore(score);
  if (s < AI_LABEL_RANGES.human.max) return "human";
  if (s < AI_LABEL_RANGES.ai_assisted.max) return "ai_assisted";
  return "ai_generated";
}

/** Share of the human per-stream rate a track earns, as a percentage. */
export function payoutRatePercent(score: number): number {
  return 100 - clampScore(score);
}
