import { fileURLToPath } from "node:url";

/**
 * Files the API needs at runtime, found relative to apps/api. This module sits directly in src/, and the
 * production bundle sits directly in dist/, so the same relative path works from either.
 */
const apiRoot = new URL("..", import.meta.url);

/** Database migrations (generated by drizzle-kit). */
export const migrationsDir = fileURLToPath(new URL("drizzle", apiRoot));

/** The built web app, served from the same origin in production. */
export const webDistDir = fileURLToPath(new URL("../web/dist", apiRoot));
